name: transformer-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - torch==2.5.1
      - numpy
      - pandas
      - matplotlib
      - jaxtyping
      - kagglehub
      - ipykernel
      - jupyter
